[toolchain]
package_manager = "Yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
anchor_escrow = "BW3T7qvk1DH9Yg76WjRRcLbxM1jQht4sLCqKM8FeseWj"

[programs.localnet]
anchor_escrow = "BW3T7qvk1DH9Yg76WjRRcLbxM1jQht4sLCqKM8FeseWj"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "./TVhxXJ3VNzMSnPmQ243fTA3nSSPeTS1ruU8oxRGTwzP.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
